// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualPark.DataAccess;

#nullable disable

namespace VirtualPark.DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20251114183522_AddPreventiveMaintenanceType")]
    partial class AddPreventiveMaintenanceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RankingUsers", b =>
                {
                    b.Property<Guid>("RankingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RankingId", "UserId");

                    b.HasIndex("RankingId");

                    b.HasIndex("UserId");

                    b.ToTable("RankingUsers", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Attractions.Entity.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVisitors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.AttractionsEvents.Entity.AttractionEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "AttractionId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("EventId");

                    b.ToTable("AttractionEvents", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.ClocksApp.Entity.ClockApp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateSystem")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ClockApp", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Events.Entity.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Incidences.Entity.Incidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TypeIncidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("TypeIncidenceId");

                    b.ToTable("Incidences", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Permissions.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving details of a specific user",
                            Key = "GetUserById-User"
                        },
                        new
                        {
                            Id = new Guid("10101010-1111-1111-1111-111111111112"),
                            Description = "Allows listing all users",
                            Key = "GetAllUsers-User"
                        },
                        new
                        {
                            Id = new Guid("10101010-1111-1111-1111-111111111113"),
                            Description = "Allows updating user data",
                            Key = "UpdateUser-User"
                        },
                        new
                        {
                            Id = new Guid("10101010-1111-1111-1111-111111111114"),
                            Description = "Allows deleting a user",
                            Key = "DeleteUser-User"
                        },
                        new
                        {
                            Id = new Guid("10101010-1111-1111-1111-111111111115"),
                            Description = "Allows creating new users",
                            Key = "CreateUser-User"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving details of a specific attraction",
                            Key = "GetAttractionById-Attraction"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Description = "Allows creating attractions",
                            Key = "CreateAttraction-Attraction"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Description = "Allows listing all attractions",
                            Key = "GetAllAttractions-Attraction"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Description = "Allows updating attraction data",
                            Key = "UpdateAttraction-Attraction"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Description = "Allows deleting an attraction",
                            Key = "DeleteAttraction-Attraction"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving details of a specific event",
                            Key = "GetEventById-Event"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111112"),
                            Description = "Allows creating events",
                            Key = "CreateEvent-Event"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111113"),
                            Description = "Allows listing all events",
                            Key = "GetAllEvents-Event"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111114"),
                            Description = "Allows updating event data",
                            Key = "UpdateEvent-Event"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111115"),
                            Description = "Allows deleting an event",
                            Key = "DeleteEvent-Event"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving a ticket by ID",
                            Key = "GetTicketById-Ticket"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111112"),
                            Description = "Allows creating tickets",
                            Key = "CreateTicket-Ticket"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111113"),
                            Description = "Allows listing all tickets",
                            Key = "GetAllTickets-Ticket"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111114"),
                            Description = "Allows deleting a ticket",
                            Key = "DeleteTicket-Ticket"
                        },
                        new
                        {
                            Id = new Guid("12121212-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving visitor profile",
                            Key = "GetVisitorProfileById-VisitorProfile"
                        },
                        new
                        {
                            Id = new Guid("12121212-1111-1111-1111-111111111112"),
                            Description = "Allows updating visitor profile",
                            Key = "UpdateVisitorProfile-VisitorProfile"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving an incidence",
                            Key = "GetIncidenceById-Incidence"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111112"),
                            Description = "Allows creating incidences",
                            Key = "CreateIncidence-Incidence"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111113"),
                            Description = "Allows listing incidences",
                            Key = "GetAllIncidences-Incidence"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111114"),
                            Description = "Allows updating incidence info",
                            Key = "UpdateIncidence-Incidence"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111115"),
                            Description = "Allows deleting incidences",
                            Key = "DeleteIncidence-Incidence"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving a type incidence",
                            Key = "GetTypeIncidenceById-TypeIncidence"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111112"),
                            Description = "Allows listing all type incidences",
                            Key = "GetAllTypeIncidences-TypeIncidence"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111113"),
                            Description = "Allows creating type incidences",
                            Key = "CreateTypeIncidence-TypeIncidence"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111114"),
                            Description = "Allows updating type incidences",
                            Key = "UpdateTypeIncidence-TypeIncidence"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111115"),
                            Description = "Allows deleting type incidences",
                            Key = "DeleteTypeIncidence-TypeIncidence"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving a strategy",
                            Key = "GetStrategyById-Strategy"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111112"),
                            Description = "Allows listing all strategies",
                            Key = "GetAllStrategies-Strategy"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111113"),
                            Description = "Allows creating strategies",
                            Key = "CreateStrategy-Strategy"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111114"),
                            Description = "Allows updating strategies",
                            Key = "UpdateStrategy-Strategy"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111115"),
                            Description = "Allows deleting strategies",
                            Key = "DeleteStrategy-Strategy"
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving ranking by period",
                            Key = "GetRankingByPeriod-Ranking"
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-1111-111111111112"),
                            Description = "Allows listing all rankings",
                            Key = "GetAllRankings-Ranking"
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving a role",
                            Key = "GetRoleById-Role"
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111112"),
                            Description = "Allows creating roles",
                            Key = "CreateRole-Role"
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111113"),
                            Description = "Allows listing roles",
                            Key = "GetAllRoles-Role"
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111114"),
                            Description = "Allows updating roles",
                            Key = "UpdateRole-Role"
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111115"),
                            Description = "Allows deleting roles",
                            Key = "DeleteRole-Role"
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving a permission",
                            Key = "GetPermissionById-Permission"
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111112"),
                            Description = "Allows creating permissions",
                            Key = "CreatePermission-Permission"
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111113"),
                            Description = "Allows listing permissions",
                            Key = "GetAllPermissions-Permission"
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111114"),
                            Description = "Allows updating permissions",
                            Key = "UpdatePermission-Permission"
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111115"),
                            Description = "Allows deleting permissions",
                            Key = "DeletePermission-Permission"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111111"),
                            Description = "Allows retrieving details of a specific reward",
                            Key = "GetRewardById-Reward"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111112"),
                            Description = "Allows creating new rewards",
                            Key = "CreateReward-Reward"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111113"),
                            Description = "Allows listing all rewards",
                            Key = "GetAllRewards-Reward"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111114"),
                            Description = "Allows updating rewards",
                            Key = "UpdateReward-Reward"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111115"),
                            Description = "Allows deleting rewards",
                            Key = "DeleteReward-Reward"
                        },
                        new
                        {
                            Id = new Guid("56565656-1111-1111-1111-111111111111"),
                            Description = "Allows redeeming rewards",
                            Key = "RedeemReward-RewardRedemption"
                        },
                        new
                        {
                            Id = new Guid("56565656-1111-1111-1111-111111111112"),
                            Description = "Allows retrieving a specific reward redemption",
                            Key = "GetRewardRedemptionById-RewardRedemption"
                        },
                        new
                        {
                            Id = new Guid("56565656-1111-1111-1111-111111111113"),
                            Description = "Allows listing all reward redemptions",
                            Key = "GetAllRewardRedemptions-RewardRedemption"
                        },
                        new
                        {
                            Id = new Guid("56565656-1111-1111-1111-111111111114"),
                            Description = "Allows retrieving redemptions of a specific visitor",
                            Key = "GetRewardRedemptionsByVisitor-RewardRedemption"
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-1111-111111111114"),
                            Description = "Allows update clockApp",
                            Key = "UpdateClock-ClockApp"
                        },
                        new
                        {
                            Id = new Guid("13131313-1111-1111-1111-111111111116"),
                            Description = "Allows creating active strategy",
                            Key = "CreateActiveStrategy-Strategy"
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Rankings.Entity.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rankings", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.RewardRedemptions.Entity.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("VisitorId");

                    b.ToTable("RewardRedemptions", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Rewards.Entity.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("RequiredMembershipLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.RolePermissions.Entity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("12121212-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("12121212-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("13131313-1111-1111-1111-111111111116")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("88888888-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("88888888-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("99999999-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("99999999-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("99999999-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("99999999-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("99999999-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("88888888-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111115")
                        },
                        new
                        {
                            RoleId = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("12121212-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("12121212-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("88888888-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("88888888-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("56565656-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("56565656-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10101010-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            RoleId = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("22222222-1111-1111-1111-111111111113")
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Roles.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Description = "Full system access",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("bbbb1111-1111-1111-1111-111111111111"),
                            Description = "Attraction operator",
                            Name = "Operator"
                        },
                        new
                        {
                            Id = new Guid("cccc1111-1111-1111-1111-111111111111"),
                            Description = "Regular park visitor",
                            Name = "Visitor"
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Sessions.Entity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Strategy.Entity.ActiveStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ActiveStrategies", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Tickets.Entity.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("VisitorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("QrId")
                        .IsUnique();

                    b.HasIndex("VisitorProfileId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.TypeIncidences.Entity.TypeIncidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("TypeIncidences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Type = "PREVENTIVE_MAINTENANCE"
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.UserRoles.Entity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaa9999-1111-1111-1111-111111111111"),
                            RoleId = new Guid("aaaa1111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Users.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VisitorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VisitorProfileId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa9999-1111-1111-1111-111111111111"),
                            Email = "admin@virtualpark.com",
                            LastName = "System",
                            Name = "Admin",
                            Password = "Admin123!"
                        });
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitRegistrations.Entity.VisitRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitRegistrations", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitorsProfile.Entity.VisitorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Membership")
                        .HasColumnType("int");

                    b.Property<Guid>("NfcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VisitorsProfile");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitsRegistrationsAttractions.Entity.VisitRegistrationAttraction", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttractionId", "VisitRegistrationId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("VisitRegistrationId");

                    b.ToTable("VisitRegistrationsAttractions", (string)null);
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitsScore.Entity.VisitScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayStrategyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("VisitRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Origin");

                    b.HasIndex("VisitRegistrationId");

                    b.ToTable("VisitScores", (string)null);
                });

            modelBuilder.Entity("RankingUsers", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Rankings.Entity.Ranking", null)
                        .WithMany()
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.Users.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.AttractionsEvents.Entity.AttractionEvent", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Attractions.Entity.Attraction", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.Events.Entity.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Incidences.Entity.Incidence", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Attractions.Entity.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.TypeIncidences.Entity.TypeIncidence", "Type")
                        .WithMany()
                        .HasForeignKey("TypeIncidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.RewardRedemptions.Entity.RewardRedemption", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Rewards.Entity.Reward", null)
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.VisitorsProfile.Entity.VisitorProfile", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.RolePermissions.Entity.RolePermission", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Permissions.Entity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.Roles.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Sessions.Entity.Session", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Users.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Tickets.Entity.Ticket", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Events.Entity.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VirtualPark.BusinessLogic.VisitorsProfile.Entity.VisitorProfile", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.UserRoles.Entity.UserRole", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Roles.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.Users.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.Users.Entity.User", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.VisitorsProfile.Entity.VisitorProfile", "VisitorProfile")
                        .WithMany()
                        .HasForeignKey("VisitorProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VisitorProfile");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitRegistrations.Entity.VisitRegistration", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Tickets.Entity.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.VisitorsProfile.Entity.VisitorProfile", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitsRegistrationsAttractions.Entity.VisitRegistrationAttraction", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.Attractions.Entity.Attraction", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualPark.BusinessLogic.VisitRegistrations.Entity.VisitRegistration", null)
                        .WithMany()
                        .HasForeignKey("VisitRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitsScore.Entity.VisitScore", b =>
                {
                    b.HasOne("VirtualPark.BusinessLogic.VisitRegistrations.Entity.VisitRegistration", "VisitRegistration")
                        .WithMany("ScoreEvents")
                        .HasForeignKey("VisitRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRegistration");
                });

            modelBuilder.Entity("VirtualPark.BusinessLogic.VisitRegistrations.Entity.VisitRegistration", b =>
                {
                    b.Navigation("ScoreEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
